create about page
CoderSpace/service pull request #2
Opened 2017-07-27 20:03 UTC by genejolivet8

2017-07-27 20:10 UTC, kallatt approved these changes

2017-07-27 20:11 UTC, Brice22 approved these changes

2017-07-27 20:11 UTC, Andrewth3giant approved these changes

2017-07-28 03:58 UTC, arelia requested changes
looking good! 👍

2017-07-28 03:58 UTC, arelia commented on styles/about.css
> +    background-color:;
make sure to add a color value here, or comment this out

2017-07-28 15:30 UTC, arelia approved these changes

2017-07-28 15:31 UTC, merged